### ISSUE TITLE
Need update in line 210 in Sample_data.py

### ISSUE THREAD

**Issue by ujjawal61** [edvinli/federated-learning-mixture#1]
Need to update the parameter from true to False in line 211 in sample_data.py. Otherwise it will only work for less number of users.

**Comment by edvinli** [comment]
Do you mean line 210? Then yes, right now it is implemented as in the paper which means you will need to have num_users equal to num_classes/2, since each user will have 2 classes each and with no overlap. If you change the line from False to True and thus allowing sampling with replacement, you can have any number of users, allowing for overlap of classes between users.
